sudo: required
services:
- docker
language: python
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
  matrix:
  - GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin
    PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1
  global:
    secure: cOnxkw37k6yRN15iyjTsqcf8dHlcqdRuQ9waY2olv0Zv01KFgltr45qj504nS609K2nFPVRdOrbkJAMOVesjVulDKwJGwj4njgfL0DNQCeGoQigjoKIRZ1C+Mx14F54cM6n2BcTuLw0OjcAHA5o11Y8haky1d8NJIwBPfj8p/kY4s9wBeTyw/+g8QF3cBHYAMUPkGBRGfZNLqO3J4XRpbwo/NkGMhYI3FhHRUR10jtCZx8y2Uy2hMzLmsQHYHLPt4+o7xFDLujDm6OKZaQP/RXFvAIBQ0XqCBE/TMeyIK1knTj0DwLVeXKaVrTIc376/9f+KhZsv0XCT1Izamk16xmKovSz2FGBz7VDFq9YoF0qQlZ2cQMjL7/42Tas3rUymQmJECALqX34Nd8OvNDcSPuThe475zYrk7ZRhpUjRkfmV1XCkPLUmssVE5NLwqCXoSRdjXwsDHr1vdcqnBicicdp1AW/KqSij/X2u0W3DadJORymPHxq4b9SCtGxzCjwYXHuLX/2sB9zqYBEMin9P43kKr2I/XIXWpwc7UvHQHaIkSGv3Rcajx8L/SqaUMLN/A5BC+uJnFsxMZMWGH/ZG4PmDTd7Xbr5egpjivZC6lrPDYsWyFW6HfWT3sOJz0sMLzllbRS3mw0s55zD1NCLC+Si2Y4ywD2gAWQZcVsp5exA=
before_install:
- openssl aes-256-cbc -K $encrypted_ce57a6517705_key -iv $encrypted_ce57a6517705_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d "${GAE_PYTHONPATH}" ]; then python scripts/fetch_gae_sdk.py $(dirname
  "${GAE_PYTHONPATH}"); fi
- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
  fi
- tar -xzf credentials.tar.gz
- mkdir -p lib
- gcloud auth activate-service-account --key-file client-secret.json
install:
- gcloud config set project geariot-air
- gcloud -q components update gae-python
- pip install -r requirements.txt -t lib/
script:
- gcloud -q preview app deploy app.yaml --promote --project geariot-ait
