runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.app
  
- url: /index\.html
  script: main.app
  
- url: /images
  static_dir: images
  
- url: /(.*\.(gif|png|jpg))$
  static_files: images/\1
  upload: static/.*\.(gif|png|jpg)$
  
- url: /css
  static_dir: css

- url: /update
  static_dir: update

- url: /(.*\.(bin))$
  static_files: update/\1
  upload: update/.*\.(bin)$
  
- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
